spring.application.name=upSkillConnect-api
spring.datasource.url=jdbc:postgresql://localhost:5432/UpSkillConnect
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true